export function fetchCSExportData(_clientId) {
  return {
    countsAsOf: new Date("2024-08-01"),
    clientName: "QUESTCO TEST",
    clientDBA: "DEMO CLIENT",
    clientNumber: "102",
    readyForClient: true,
    benefitContact: {
      name: "Test Contact",
      email: "test@questco.net",
      phone: "(936) 756-1980",
    },
    benefitRep: {
      name: "",
      email: "",
      phone: "",
    },
    benefitYear: 2025,
  };
}

export function fetchClassesPlansData(_clientId) {
  return {
    classes: [
      {
        name: "MANAGERS",
        code: "2 (Non-Renewal)",
        currentHealthCount: 28,
        currentDentalCount: 6,
        currentVisionCount: 4,
        renewalHealthCount: 0,
        renewalDentalCount: 0,
        renewalVisionCount: 0,
        renewalSTDCount: 0,
        renewalLTDCount: 0,
        renewalLifeCount: 0,
      },
      {
        name: "OWNERS",
        code: "3 (Non-Renewal)",
        currentHealthCount: 28,
        currentDentalCount: 6,
        currentVisionCount: 4,
        renewalHealthCount: 0,
        renewalDentalCount: 0,
        renewalVisionCount: 0,
        renewalSTDCount: 0,
        renewalLTDCount: 0,
        renewalLifeCount: 0,
      },
      {
        name: "PRIMARY",
        code: "1 (Non-Renewal)",
        currentHealthCount: 28,
        currentDentalCount: 6,
        currentVisionCount: 4,
        renewalHealthCount: 0,
        renewalDentalCount: 0,
        renewalVisionCount: 0,
        renewalSTDCount: 0,
        renewalLTDCount: 0,
        renewalLifeCount: 0,
      },
    ],
    questcoEAP: true,
    eapRate: 2.5,
  };
}

export function fetchCurrentPlansData(_clientId) {
  return {
    health: [
      {
        primaryKey: "H-001",
        planClass: "MANAGERS",
        planID: "BCBS-500",
        uniquePlanCode: "BCBS500-T1",
        carrier: "Blue Cross Blue Shield",
        riskTier: "Standard",
        benefitGroup: "Group A",
        eo: 450.0,
        es: 900.0,
        ec: 850.0,
        ek: 0,
        fam: 1350.0,
        eoCount: 15,
        esCount: 5,
        ekCount: 0,
        ecCount: 4,
        famCount: 4,
        eoContrib: 400.0,
        esContrib: 700.0,
        ecContrib: 650.0,
        ekContrib: 0,
        famContrib: 1000.0,
        inCoinsurance: 0.8,
        inDedIndiv: 500.0,
        inDedFam: 1500.0,
        inOopMaxIndiv: 4000.0,
        inOopMaxFam: 8000.0,
        officeVisitPCP: 30.0,
        officeVisitSpecialist: 50.0,
        advancedRadiology: 250.0,
        hospitalInpatient: 500.0,
        surgeryOutpatient: 300.0,
        emergencyRoom: 150.0,
        urgentCare: 50.0,
        pharmacyDedAmt: 0,
        pharmacyGeneric: 10.0,
        pharmacyFormulary: 35.0,
        pharmacyNonFormulary: 70.0,
        pharmacySpecialty: 150.0,
        pharmacyMailOrder: 25.0,
        oonCoinsurance: 0.6,
        oonDedIndiv: 1000.0,
        oonDedFam: 3000.0,
        oonOopMaxIndiv: 8000.0,
        oonOopMaxFam: 16000.0,
        healthLabs: 0,
        healthDiagnosticXray: 0,
      },
    ],
    dental: [
      {
        primaryKey: "D-001",
        planClass: "MANAGERS",
        planID: "MET-D100",
        uniquePlanCode: "METD100-T1",
        carrier: "MetLife",
        riskTier: "Standard",
        benefitGroup: "Group A",
        eo: 45.0,
        es: 85.0,
        ec: 80.0,
        ek: 0,
        fam: 130.0,
        eoCount: 10,
        esCount: 3,
        ekCount: 0,
        ecCount: 2,
        famCount: 1,
        eoContrib: 45.0,
        esContrib: 50.0,
        ecContrib: 45.0,
        ekContrib: 0,
        famContrib: 60.0,
        inOrthodontiaPctDollar: 0.5,
        inOrthodontiaMax: 1500.0,
        oonDedIndiv: 50.0,
        oonDedFam: 150.0,
        oonPreventativeCare: 1.0,
        oonBasicRestorative: 0.8,
        oonMajorRestorative: 0.5,
        annualDentalMax: 2000.0,
      },
    ],
    vision: [
      {
        primaryKey: "V-001",
        planClass: "MANAGERS",
        planID: "VSP-100",
        uniquePlanCode: "VSP100-T1",
        carrier: "VSP",
        riskTier: "Standard",
        benefitGroup: "Group A",
        eo: 12.0,
        es: 22.0,
        ec: 20.0,
        ek: 0,
        fam: 35.0,
        eoCount: 8,
        esCount: 4,
        ekCount: 0,
        ecCount: 2,
        famCount: 2,
        eoContrib: 12.0,
        esContrib: 12.0,
        ecContrib: 12.0,
        ekContrib: 0,
        famContrib: 12.0,
        inFreqFrames: "24 months",
        inSingleVisionLenses: 25.0,
        inBifocalLenses: 25.0,
        inTrifocalLenses: 25.0,
        inFrames: 150.0,
        inContactLensesNoFrames: 150.0,
        oonCopayExam: 45.0,
        oonCopayContactExam: 45.0,
        oonCopayMaterials: 0,
        oonSingleVisionLenses: 30.0,
        oonBifocalLenses: 50.0,
        oonTrifocalLenses: 65.0,
        oonFrames: 70.0,
        oonContactLensesNoFrames: 105.0,
      },
    ],
    other: [
      {
        primaryKey: "O-001",
        category: "Supplemental",
        planClass: "MANAGERS",
        planID: "SUP-001",
        uniquePlanCode: "SUP001-T1",
        carrier: "Aflac",
        riskTier: "Standard",
        benefitGroup: "Group A",
        eo: 15.0,
        es: 25.0,
        ek: 0,
        ec: 22.0,
        fam: 40.0,
        eoCount: 5,
        ekCount: 0,
        esCount: 2,
        ecCount: 1,
        famCount: 1,
        eoContrib: 0,
        esContrib: 0,
        ecContrib: 0,
        ekContrib: 0,
        famContrib: 0,
      },
    ],
  };
}

export function fetchRenewalPlansData(_clientId) {
  return {
    health: [
      {
        renewedFromPrimaryKey: "H-001",
        planClass: "MANAGERS",
        planID: "BCBS-600",
        renewedFromPlan: "BCBS-500",
        uniquePlanCode: "BCBS600-T1",
        carrier: "Blue Cross Blue Shield",
        riskTier: "Standard",
        benefitGroup: "Group A",
        effectiveDate: new Date("2025-01-01"),
        contributionMethod: "Flat Dollar",
        eo: 475.0,
        es: 950.0,
        ec: 900.0,
        ek: 0,
        fam: 1425.0,
        eoCount: 15,
        esCount: 5,
        ecCount: 4,
        ekCount: 0,
        famCount: 4,
        eoContrib: 425.0,
        esContrib: 750.0,
        ecContrib: 700.0,
        famContrib: 1050.0,
        ekContrib: 0,
        inCoinsurance: 0.8,
        inDedIndiv: 500.0,
        inDedFam: 1500.0,
        inOopMaxIndiv: 4500.0,
        inOopMaxFam: 9000.0,
        officeVisitPCP: 30.0,
        officeVisitSpecialist: 55.0,
        advancedRadiology: 275.0,
        hospitalInpatient: 500.0,
        surgeryOutpatient: 350.0,
        emergencyRoom: 175.0,
        urgentCare: 50.0,
        pharmacyDedAmt: 0,
        pharmacyGeneric: 15.0,
        pharmacyFormulary: 40.0,
        pharmacyNonFormulary: 75.0,
        pharmacySpecialty: 175.0,
        pharmacyMailOrder: 30.0,
        oonCoinsurance: 0.6,
        oonDedIndiv: 1000.0,
        oonDedFam: 3000.0,
        oonOopMaxIndiv: 9000.0,
        oonOopMaxFam: 18000.0,
        labs: 0,
        diagnosticXray: 0,
      },
    ],
    dental: [
      {
        renewedFromPrimaryKey: "D-001",
        planClass: "MANAGERS",
        planID: "MET-D200",
        renewedFromPlan: "MET-D100",
        uniquePlanCode: "METD200-T1",
        carrier: "MetLife",
        riskTier: "Standard",
        benefitGroup: "Group A",
        effectiveDate: new Date("2025-01-01"),
        contributionMethod: "Flat Dollar",
        eo: 48.0,
        es: 90.0,
        ec: 85.0,
        ek: 0,
        fam: 140.0,
        eoCount: 10,
        esCount: 3,
        ecCount: 2,
        ekCount: 0,
        famCount: 1,
        eoContrib: 48.0,
        esContrib: 55.0,
        ecContrib: 50.0,
        famContrib: 65.0,
        ekContrib: 0,
        inDedIndiv: 0,
        inDedFam: 0,
        inPreventativeCare: 1.0,
        inBasicRestorative: 0.8,
        inMajorRestorative: 0.5,
        inOrthodontiaPctDollar: 0.5,
        inOrthodontiaMax: 1500.0,
        oonDedIndiv: 50.0,
        oonDedFam: 150.0,
        oonPreventativeCare: 1.0,
        oonBasicRestorative: 0.8,
        oonMajorRestorative: 0.5,
        annualDentalMax: 2000.0,
      },
    ],
    vision: [
      {
        renewedFromPrimaryKey: "V-001",
        planClass: "MANAGERS",
        planID: "VSP-200",
        renewedFromPlan: "VSP-100",
        uniquePlanCode: "VSP200-T1",
        carrier: "VSP",
        riskTier: "Standard",
        benefitGroup: "Group A",
        effectiveDate: new Date("2025-01-01"),
        contributionMethod: "Flat Dollar",
        eo: 13.0,
        es: 24.0,
        ec: 22.0,
        ek: 0,
        fam: 38.0,
        eoCount: 8,
        esCount: 4,
        ecCount: 2,
        ekCount: 0,
        famCount: 2,
        eoContrib: 13.0,
        esContrib: 13.0,
        ecContrib: 13.0,
        famContrib: 13.0,
        ekContrib: 0,
        inCopayExam: 10.0,
        inCopayContactExam: 10.0,
        inCopayMaterials: 25.0,
        inFreqEyeExam: "12 months",
        inFreqReplacementLenses: "12 months",
        inFreqFrames: "24 months",
        inSingleVisionLenses: 25.0,
        inBifocalLenses: 25.0,
        inTrifocalLenses: 25.0,
        inFrames: 150.0,
        inContactLensesNoFrames: 150.0,
        oonCopayExam: 50.0,
        oonCopayContactExam: 50.0,
        oonCopayMaterials: 0,
        oonSingleVisionLenses: 30.0,
        oonBifocalLenses: 50.0,
        oonTrifocalLenses: 65.0,
        oonFrames: 70.0,
        oonContactLensesNoFrames: 105.0,
      },
    ],
    std: [
      {
        renewedFromPrimaryKey: "STD-001",
        planClass: "MANAGERS",
        planID: "UNM-STD1",
        renewedFromPlan: "",
        uniquePlanCode: "UNMSTD1-T1",
        carrier: "Unum",
        riskTier: "Standard",
        benefitGroup: "Group A",
        effectiveDate: new Date("2025-01-01"),
        contributionMethod: "Employer Paid",
        eo: 8.5,
        es: 0,
        ec: 0,
        ek: 0,
        fam: 0,
        eoCount: 28,
        esCount: 0,
        ecCount: 0,
        ekCount: 0,
        famCount: 0,
        eoContrib: 8.5,
        esContrib: 0,
        ecContrib: 0,
        famContrib: 0,
        ekContrib: 0,
        benefitPercentage: 0.6,
        maximumWeeklyBenefit: 1000.0,
        benefitDuration: "26 weeks",
        illness: "7 days",
        accident: "0 days",
        definitionOfDisability: "Own Occupation",
        preExistingLimitation: "3/12",
        teleguard: "No",
        returnToWork: "Yes",
        rehabServices: "Yes",
        coverageType: "24 Hour",
      },
    ],
    ltd: [
      {
        renewedFromPrimaryKey: "LTD-001",
        planClass: "MANAGERS",
        planID: "UNM-LTD1",
        renewedFromPlan: "",
        uniquePlanCode: "UNMLTD1-T1",
        carrier: "Unum",
        riskTier: "Standard",
        benefitGroup: "Group A",
        effectiveDate: new Date("2025-01-01"),
        contributionMethod: "Employer Paid",
        eo: 12.0,
        es: 0,
        ec: 0,
        ek: 0,
        fam: 0,
        eoCount: 28,
        esCount: 0,
        ecCount: 0,
        ekCount: 0,
        famCount: 0,
        eoContrib: 12.0,
        esContrib: 0,
        ecContrib: 0,
        famContrib: 0,
        ekContrib: 0,
        benefitPercentage: 0.6,
        monthlyBenefitMaximum: 6000.0,
        monthlyBenefitMinimum: 100.0,
        eliminationPeriod: "180 days",
        socialSecurityIntegration: "All Sources",
        survivorBenefit: "3 months",
        benefitDuration: "SSNRA",
        preExisting: "3/12",
        mentalNervousSubstance: "24 months",
        disabilityDefinition: "Own Occ 24 months, then Any Occ",
      },
    ],
    life: [
      {
        renewedFromPrimaryKey: "LIFE-001",
        planClass: "MANAGERS",
        planID: "UNM-LIFE1",
        renewedFromPlan: "",
        uniquePlanCode: "UNMLIFE1-T1",
        carrier: "Unum",
        riskTier: "Standard",
        benefitGroup: "Group A",
        effectiveDate: new Date("2025-01-01"),
        contributionMethod: "Employer Paid",
        eo: 5.0,
        es: 0,
        ec: 0,
        ek: 0,
        fam: 0,
        eoCount: 28,
        esCount: 0,
        ecCount: 0,
        ekCount: 0,
        famCount: 0,
        eoContrib: 5.0,
        esContrib: 0,
        ecContrib: 0,
        famContrib: 0,
        ekContrib: 0,
        employeeLifeBenefitAmount: 50000.0,
        guaranteeIssueMaxBenefit: 50000.0,
        addBenefits: "Included",
        acceleratedDeathBenefit: "Included",
        waiverOfPremium: "Included",
        portability: "Included",
        conversion: "Included",
        ageReductions: "65% at 65, 50% at 70",
        commonCarrier: "Not Included",
      },
    ],
    other: [],
  };
}
